version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - copyloopvar
    - decorder
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - godot
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - prealloc
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    exhaustive:
      default-signifies-exhaustive: true
    gocognit:
      min-complexity: 160
    goconst:
      min-len: 2
      min-occurrences: 2
    nestif:
      min-complexity: 10
    nolintlint:
      require-explanation: true
      require-specific: true
    wsl:
      allow-assign-and-anything: true
      allow-cuddle-declarations: true
      force-err-cuddling: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
