services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      pg:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - GO_ENV=production

  pg:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db2sem
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db2sem"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
