// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package pg

import (
	"context"
)

const getSportsmen = `-- name: GetSportsmen :many
SELECT id, name, birth_date, height_cm, weight_kg, club_id, created_at
FROM sportsmen
`

func (q *Queries) GetSportsmen(ctx context.Context) ([]Sportsman, error) {
	rows, err := q.db.Query(ctx, getSportsmen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sportsman
	for rows.Next() {
		var i Sportsman
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BirthDate,
			&i.HeightCm,
			&i.WeightKg,
			&i.ClubID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
